version: '3'
services:
  fastapi_app:
    build: .
    env_file:
      - .env.local
    ports:
      - "7070:80"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5435:5432"
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data


  cron:
    build:
      context: ./cron
      dockerfile: Dockerfile
    depends_on:
      - fastapi_app
    env_file:
      - .env.local

volumes:
  postgres_data:
